### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by rbiggs** [developit/htm#20]
Downloaded, installed dependencies and ran `npm run build`. Got the following error:
```
> npm run -s build:main && npm run -s build:preact && npm run -s build:babel

(node:4286) Warning: N-API is an experimental feature and could change at any time.
(nodent plugin) Error: Plugin 'jsx' not found
Error: Plugin 'jsx' not found
    at Parser.loadPlugins (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/node_modules/acorn/dist/acorn.js:543:26)
    at new Parser (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/node_modules/acorn/dist/acorn.js:469:8)
    at Object.parse (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/node_modules/acorn/dist/acorn.js:5288:10)
    at acornParse (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/compiler.js:37:21)
    at NodentCompiler.parseCode [as parse] (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/compiler.js:177:17)
    at NodentCompiler.compile (/Users/rbiggs/Github/htm-master/node_modules/nodent-compiler/compiler.js:112:19)
    at Object.transform (/Users/rbiggs/Github/htm-master/node_modules/rollup-plugin-nodent/index.js:35:25)
    at /Users/rbiggs/Github/htm-master/node_modules/rollup/dist/rollup.js:20847:25
    at <anonymous>
```

**Comment by developit** [comment]
Yeah, been stuck on that one. I'm using yarn for installation as a workaround in the meantime. 

https://github.com/developit/microbundle/issues/74

**Comment by rbiggs** [comment]
I'm thinking it's a problem with microbundler. I switched it out for rollup and no problem.
